language: node_js
sudo: false
node_js: 'lts/*'
cache: yarn
env:
  global:
    secure: eMzPfJSrLuDVCILlalM1QY7cuQn8PjZuKtY3u7y/3EUvb5XKg0TojJSyDGQNKuHCSonSByuR5AP68VzCZBC5YSWiTwSCRysppr5/PyQcojRTEehET+AOS7MWlZprDsrF3KsP5OmLS4fbVIkD/FklIOxCvALcSGmN/ZIavPk42dYcKAd63oYjijR/34VXyBaQ/LEhwgnsQ+arKAiuHCc0KADbw+qnqKuMNwBIv/VzNJdMLK+8qPew0AEhQSEZm8v1ihaobLqKq+Oif43ft8ldS6L92kTnZCaCFgGPUGa398E9FJcqcct5m+I2A6T9VN0AL8RB61T7r/M9ow6sYTQW5KnunX+ZPGKergtP9yrmd9PaMv5xr+vMIYUTyw2bQos8f/hkXd+BXS0V5PvpQ1aLZZH0YYx++GFAMRdVnBfZaMKXrH0VWyHlt4TRMxab7PmuWE5w/vymCl29DHLdiLO9syM4rvvrVXJVe1hw2rjuNsprp4KSbCrDlgvkIsql5BourjA8pOeP8U56Mo/PPtNLbgza4DNqmtu+pdg8Qh1Xd6i7/bBYJRBQuHjuXTLy60r42rZvnkO0TINv47HUyzed0DM3DnaWnYlvkV89ZQzaMAa7z77fPYbB5dTzFrGGOvtGg/kJd/sVyI2ojQ7elK88tU6/Wk+vX2Hlff/INOkIQJE=
jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script:
      - npm run test
      - npm run coverage
    - stage: Sauce
      script: npm run ci:sauce
      if: type = pr
notifications:
  email: false
  slack:
    secure: U3uzO3B/0Ri3MeHJANkJwMNzEw6hrErULn26VPQvyQJ0k0FwjziUt9/rNy2dl1U1Nn378zz27aA+r3IA7MmxNZL09QoJuvwbRkXFm+GlQoN53dJkH/q3M/Hvak1A+ET2f537Ak9IfOGJa++aEPr6Pk0MC/abts0tDv1YVCic9uZMsJV8fBQX338lvHKJStwuHHCjlz3HmwoJZtilgpwtHlPl1UwAL6h3885Qm+mZ9pt6PGSy619ac39gF3dVKtw459wctwvlM5GJq8A+ixMlUrQhOnNtKuccKcUkyjxTFZ7iLPM3OODF4UYzoLm6+m/6wN1SlxPM+zinq1ugb+5b41axpWJrBAyj1KUIKzxJRbE0tIGfAVHopkJifwmuU+ypbHFQnxCg49+VSUyNrasuRIhwmIiRq0weYELgDVtu4O1hwp4UHokpd5OJ4eSdKWAt8qScaFBqZSgWkm8uMa6N2qQWfVA4uHaTS67uYfghxhbAtbR1IhsBwCbKiG2hl9MxZ0BFa+9/1NWIC61LnEtB7lo6fO4K2TpqR7lZ75+/RELROBAehdoI5iQqbUxe40PFePKDr8fCXDUaTs6al+35l+pYLPFz2dI8ave8TSlSYK4RFfdpZlM/Db4mHcI8FGc5woI+hc6u5jvT5cj71abMAqQ+Lwl4NcfjjJkAWq63PYU=
before_deploy:
- npm run build
deploy:
- provider: script
  script: scripts/publish
  skip_cleanup: true
  on:
    tags: true
    repo: userdive/agent.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJGRQLUF4DJQRRPGA
  secret_access_key:
    secure: aTQLdKpTJORmb60PYD20AAp8D7hc6J9slNHewuqUcfIWO7KVq7PQovvJ0gRaBIcz3uPd0SZ5u8/sfrO4YXH4ChiFje/Qgwsgci6nqEwKtIULCqTNREkkTPqKKssYYq/6d3a35+9oXHsRroUa2qybX4YJHk6IXmY7QhQryn2RIN6eXpCX9pGnji7Ql30cq9QaH3sstE4pvjZux71+U6ee7OZtRJxZ13TvGQLGdhziQog10/8QVlRKgwQzYSIu5Ikga01I+ToMlkjJVGqku4KDCvXIdz7IL9KvUYIGgNGPeDIBy2rVNeP95UhYcPu9W41CM5zMVT0aO0n7CdfJ7/zoWkiI4O3uxOkmLk9noVzApClSVsYWTTz7uGJumPgM/URYlboxLoSA6PcSwvtQhrJ0RZTNtFpYPfreSveQhaQFF8F80S9C1ZSPBInMJB386Hp6/9a9ZZ9pbwK+zzKVAX2lNv+F7bavi1nBFd1vrW/tfMqJfMoiynZqZWAjPQdvNnMRO2cXM8vvJg9IOixRaOcU9UE/bDL2/6gOZ5BjrDcecOuLfTwp9M0F8ISUEBlZrFvecaYHKXZYoT8vHxW4APo7BCXCts/hcS2JzN3IL/U2hDtW5D030kphtTrzUmOs7J3SxMevl8m5yMjAjY2ma8Wz/y6ZHhEQ38o3atv0nwPsrzk=
  bucket: s3-bucket-cdn-s3bucket-1rr97tspu1fmp
  local-dir: cdn
  upload-dir: agent/$TRAVIS_BRANCH
  on:
    all_branches: true
    repo: userdive/agent.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJGRQLUF4DJQRRPGA
  secret_access_key:
    secure: aTQLdKpTJORmb60PYD20AAp8D7hc6J9slNHewuqUcfIWO7KVq7PQovvJ0gRaBIcz3uPd0SZ5u8/sfrO4YXH4ChiFje/Qgwsgci6nqEwKtIULCqTNREkkTPqKKssYYq/6d3a35+9oXHsRroUa2qybX4YJHk6IXmY7QhQryn2RIN6eXpCX9pGnji7Ql30cq9QaH3sstE4pvjZux71+U6ee7OZtRJxZ13TvGQLGdhziQog10/8QVlRKgwQzYSIu5Ikga01I+ToMlkjJVGqku4KDCvXIdz7IL9KvUYIGgNGPeDIBy2rVNeP95UhYcPu9W41CM5zMVT0aO0n7CdfJ7/zoWkiI4O3uxOkmLk9noVzApClSVsYWTTz7uGJumPgM/URYlboxLoSA6PcSwvtQhrJ0RZTNtFpYPfreSveQhaQFF8F80S9C1ZSPBInMJB386Hp6/9a9ZZ9pbwK+zzKVAX2lNv+F7bavi1nBFd1vrW/tfMqJfMoiynZqZWAjPQdvNnMRO2cXM8vvJg9IOixRaOcU9UE/bDL2/6gOZ5BjrDcecOuLfTwp9M0F8ISUEBlZrFvecaYHKXZYoT8vHxW4APo7BCXCts/hcS2JzN3IL/U2hDtW5D030kphtTrzUmOs7J3SxMevl8m5yMjAjY2ma8Wz/y6ZHhEQ38o3atv0nwPsrzk=
  bucket: s3-bucket-cdn-s3bucket-1rr97tspu1fmp
  local-dir: cdn
  on:
    branch: master
    repo: userdive/agent.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJF4LQ6ECJ6VAO76Q
  secret_access_key:
    secure: ghhqHQK8bSCXAvnMuPk8n+uvJQUwaS0YOouGpmPTGU5shG2gzgitfEOz93g5S3EfuDhP8n2uGJXkqb9ORTJYyOJVNRqqCHKumk8a9Sf1DGGEpU+KMcoR0H7zY/Wi0noVMDvsxR1ZIgRxwj523nOaOCn/2eSKgtz7O1kqHDVCsY5VBznbv8Z1heyS3WQT9SXe52EGmQDo1qdpYfgZMWdqiqOCnzJZQ2LZ6TWguI4EfVDgtsJ7ptWNV3Ybik3CxPLw3Ozuweqwdo9KvBOD9JeUth41jTEbSLleTtvC+nheWAW38HjCT9D1HH9caMZpfF77wQuunjjRhDXttwBDCX8nYDKL6lZ6rpeelNqmQDgQQezsXlv5ZulLzlKuH3YaVMqIVTyZRDVrdzrDc2xnGal04PB8Y1ewgp9BtX44uLk1NsvKX3rcSGV34INQWGLzKQULLH0JdX4e9tQG6OZbZokLt1gvSqCv1r6gEHuRh6+EjYo+OL85qjd1rSHhL3vga9fYhxf/CblQI1EwxDwB7nzzSVjTovnXJN7dRrmxCbfKBpq4U/xzGxmvmvHuNY9bYAiTRK+2DIf5jdatkU8+/fEYcEWUQyOB3NPXYlGYV2i7w+7ixN9Uk/aNFLQxtoxODGHEdhICZqRSF9juKQj/ECi3RFH/WLiCmhaJQJOOhKrql2Q=
  bucket: s3-bucket-cdn-s3bucket-jhnl18vt4xcz
  local-dir: cdn
  on:
    tags: true
    repo: userdive/agent.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAIFPFPDK4BGODWSXA
  secret_access_key:
    secure: Y9Y6UAVfpKl4yAbRROtMWTj4D6dIFvMdvCyDLcXnE8RGDHapp0kclDP86y0fH91/UOn7BFo2YEgw2CChmHWOXId1nJhcw6YnKtqMTzQAzDhdiEQ4BaCDzqELgwP5f96IH4hXmZ5AJIJ8kwy0cXhoL9FAoVfiX0i5srNJX5GXB34zAt2itpPoQqE3N++fn3odsxfdXUqTB2couMr/2duAzbJQEJ2eCu2JCO1bj2g0xzTPw7gHvqhheUOxHtV4i6NgvAG6ZJMHDj7JMZ4E+amh+zHhtKaFOOGlLLidhB9/DH9yh6ibzQtXHKGYZvgRhjT5b6PLWi25KnWk28vnu7+lgCOCXWpvtPNsGjRUb2bbyawY02aWh+cNUyU1qCpKeCWCjZTGfsXsokL8c6QQn9KcurPGyQj+bICJasUCLOuzXUdXS4OuJcStoh3sW+w3jJ+74RMM01XPcSCcFsJOQSvooQzByXC52kruV9PnYN76zSfcLClhsFwL5DjcvDyQh10/FKcHT0LCHwHBGR/9tu9xC7El8mqvFQtAVlEG5maA1ygyUt21tAkgTegxMAYM4ty/qm4QQ4WY8jqx1fk5zLqcET8+uzS001JfeNKjpXJH1eD2rwV3sSQ9w4qwWWmtvfLrJ5/CiL5wvoxYrNf74bSgzH1KzokBhYx37VtVVLZxyoQ=
  bucket: s3-bucket-cdn-s3bucket-9dacuvdjwe43
  local-dir: cdn
  on:
    tags: true
    repo: userdive/agent.js
