language: node_js
sudo: false
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  matrix:
  - CI_MODE=sauce
  - CI_MODE=karma
  - CI_MODE=jsdom
matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=sauce"
script:
- npm run ci:$CI_MODE
after_success:
- npm run coverage:$CI_MODE
notifications:
  email: false
