#!/bin/bash
set -eu
echo "publish to npm"

echo "setting publish account"
npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
npm config set init.author.name userdive
npm config set init.author.email develop@uncovertruth.jp
npm config set init.author.url https://www.uncovertruth.co.jp
npm whoami

echo "publish"
npm run release

echo "done."
